import { FiCpu, FiDatabase, FiLayers, FiMessageSquare, FiSearch, FiZap } from 'react-icons/fi'
import {
  SiCss,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGithub,
  SiGooglegemini,
  SiHtml5,
  SiJavascript,
  SiLangchain,
  SiLanggraph,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiOpenjdk,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiRedis,
  SiSocketdotio,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
} from 'react-icons/si'
import { VscVscode } from 'react-icons/vsc'

// One mark per technology, shared by the Skills wave and the project posters.
// Keys cover both spellings a stack gets written in ("React" / "React.js").
export const TECH_ICONS = {
  Java: SiOpenjdk,
  Python: SiPython,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  SQL: FiDatabase,
  HTML: SiHtml5,
  CSS: SiCss,
  React: SiReact,
  'React.js': SiReact,
  'Next.js': SiNextdotjs,
  'Tailwind CSS': SiTailwindcss,
  'Node.js': SiNodedotjs,
  Express: SiExpress,
  'Express.js': SiExpress,
  FastAPI: SiFastapi,
  Flask: SiFlask,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  Redis: SiRedis,
  Git: SiGit,
  GitHub: SiGithub,
  Docker: SiDocker,
  Postman: SiPostman,
  'VS Code': VscVscode,
  'Three.js': SiThreedotjs,
  WebSockets: SiSocketdotio,
  'MERN Stack': FiLayers,
  'LLM Fundamentals': FiCpu,
  LangChain: SiLangchain,
  LangGraph: SiLanggraph,
  Gemini: SiGooglegemini,
  'Gemini AI': SiGooglegemini,
  'OpenAI API': FiCpu,
  'Generative AI': FiZap,
  Prompting: FiMessageSquare,
  RAG: FiSearch,
  FAISS: FiSearch,
}
